//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMailApp.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.IDBService")]
    public interface IDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetEmployees", ReplyAction="http://tempuri.org/IDBService/GetEmployeesResponse")]
        System.Collections.Generic.List<EntitiesLibrary.Employee> GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetEmployees", ReplyAction="http://tempuri.org/IDBService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Employee>> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetTags", ReplyAction="http://tempuri.org/IDBService/GetTagsResponse")]
        System.Collections.Generic.List<EntitiesLibrary.Tag> GetTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetTags", ReplyAction="http://tempuri.org/IDBService/GetTagsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Tag>> GetTagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetMails", ReplyAction="http://tempuri.org/IDBService/GetMailsResponse")]
        System.Collections.Generic.List<EntitiesLibrary.Mail> GetMails(bool isSender, int chosenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetMails", ReplyAction="http://tempuri.org/IDBService/GetMailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Mail>> GetMailsAsync(bool isSender, int chosenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/SetMailsData", ReplyAction="http://tempuri.org/IDBService/SetMailsDataResponse")]
        void SetMailsData(EntitiesLibrary.Mail data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/SetMailsData", ReplyAction="http://tempuri.org/IDBService/SetMailsDataResponse")]
        System.Threading.Tasks.Task SetMailsDataAsync(EntitiesLibrary.Mail data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/DeleteMailsData", ReplyAction="http://tempuri.org/IDBService/DeleteMailsDataResponse")]
        void DeleteMailsData(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/DeleteMailsData", ReplyAction="http://tempuri.org/IDBService/DeleteMailsDataResponse")]
        System.Threading.Tasks.Task DeleteMailsDataAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBServiceChannel : TestMailApp.WS.IDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceClient : System.ServiceModel.ClientBase<TestMailApp.WS.IDBService>, TestMailApp.WS.IDBService {
        
        public DBServiceClient() {
        }
        
        public DBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<EntitiesLibrary.Employee> GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Employee>> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public System.Collections.Generic.List<EntitiesLibrary.Tag> GetTags() {
            return base.Channel.GetTags();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Tag>> GetTagsAsync() {
            return base.Channel.GetTagsAsync();
        }
        
        public System.Collections.Generic.List<EntitiesLibrary.Mail> GetMails(bool isSender, int chosenID) {
            return base.Channel.GetMails(isSender, chosenID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Mail>> GetMailsAsync(bool isSender, int chosenID) {
            return base.Channel.GetMailsAsync(isSender, chosenID);
        }
        
        public void SetMailsData(EntitiesLibrary.Mail data) {
            base.Channel.SetMailsData(data);
        }
        
        public System.Threading.Tasks.Task SetMailsDataAsync(EntitiesLibrary.Mail data) {
            return base.Channel.SetMailsDataAsync(data);
        }
        
        public void DeleteMailsData(int ID) {
            base.Channel.DeleteMailsData(ID);
        }
        
        public System.Threading.Tasks.Task DeleteMailsDataAsync(int ID) {
            return base.Channel.DeleteMailsDataAsync(ID);
        }
    }
}
