//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMailApp.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.ISqlDBService")]
    public interface ISqlDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlDBService/GetEmployees", ReplyAction="http://tempuri.org/ISqlDBService/GetEmployeesResponse")]
        System.Collections.Generic.List<EntitiesLibrary.Employee> GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlDBService/GetEmployees", ReplyAction="http://tempuri.org/ISqlDBService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Employee>> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlDBService/GetTags", ReplyAction="http://tempuri.org/ISqlDBService/GetTagsResponse")]
        System.Collections.Generic.List<EntitiesLibrary.Tag> GetTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlDBService/GetTags", ReplyAction="http://tempuri.org/ISqlDBService/GetTagsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Tag>> GetTagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlDBService/GetMails", ReplyAction="http://tempuri.org/ISqlDBService/GetMailsResponse")]
        System.Collections.Generic.List<EntitiesLibrary.Mail> GetMails(bool isSender, int chosenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlDBService/GetMails", ReplyAction="http://tempuri.org/ISqlDBService/GetMailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Mail>> GetMailsAsync(bool isSender, int chosenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlDBService/SetMailsData", ReplyAction="http://tempuri.org/ISqlDBService/SetMailsDataResponse")]
        void SetMailsData(EntitiesLibrary.Mail data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlDBService/SetMailsData", ReplyAction="http://tempuri.org/ISqlDBService/SetMailsDataResponse")]
        System.Threading.Tasks.Task SetMailsDataAsync(EntitiesLibrary.Mail data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlDBService/DeleteMailsData", ReplyAction="http://tempuri.org/ISqlDBService/DeleteMailsDataResponse")]
        void DeleteMailsData(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlDBService/DeleteMailsData", ReplyAction="http://tempuri.org/ISqlDBService/DeleteMailsDataResponse")]
        System.Threading.Tasks.Task DeleteMailsDataAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISqlDBServiceChannel : TestMailApp.WS.ISqlDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SqlDBServiceClient : System.ServiceModel.ClientBase<TestMailApp.WS.ISqlDBService>, TestMailApp.WS.ISqlDBService {
        
        public SqlDBServiceClient() {
        }
        
        public SqlDBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SqlDBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SqlDBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SqlDBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<EntitiesLibrary.Employee> GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Employee>> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public System.Collections.Generic.List<EntitiesLibrary.Tag> GetTags() {
            return base.Channel.GetTags();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Tag>> GetTagsAsync() {
            return base.Channel.GetTagsAsync();
        }
        
        public System.Collections.Generic.List<EntitiesLibrary.Mail> GetMails(bool isSender, int chosenID) {
            return base.Channel.GetMails(isSender, chosenID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EntitiesLibrary.Mail>> GetMailsAsync(bool isSender, int chosenID) {
            return base.Channel.GetMailsAsync(isSender, chosenID);
        }
        
        public void SetMailsData(EntitiesLibrary.Mail data) {
            base.Channel.SetMailsData(data);
        }
        
        public System.Threading.Tasks.Task SetMailsDataAsync(EntitiesLibrary.Mail data) {
            return base.Channel.SetMailsDataAsync(data);
        }
        
        public void DeleteMailsData(int ID) {
            base.Channel.DeleteMailsData(ID);
        }
        
        public System.Threading.Tasks.Task DeleteMailsDataAsync(int ID) {
            return base.Channel.DeleteMailsDataAsync(ID);
        }
    }
}
